### PR TITLE
Fixed Update post details issue#38

### PR DESCRIPTION
**Pull request by prateek-1606**
#38 resolved.
Hi @harshmangalam, i have created issues #54 #53 which i observed. Kindly check once.

### CODE REVIEW

**Review by harshmangalam — APPROVED** [review]
Approved

**Comment by harshmangalam** [comment]
Can you please remove package-lock.json because this project is using pnpm.

**Comment by prateek-1606** [comment]
@harshmangalam Done.

**Review by harshmangalam — APPROVED** [review]
Approved

**Pull request merged**
