### PR TITLE
fix issue #3

### PR DESCRIPTION
**Pull request by arsen1c**
This commit enhances the features of the Signup Button as mentioned in issue #3.

### Following are the changes made
- [x] Add spinner in signup button while loading...
- [x] Disable button during loading...
- [x] Change disable button background

### Screenshots

image

Also, the spinner is animated using the `animate-spin` class.

### CODE REVIEW

**Comment by harshmangalam** [comment]
Thanks @arsen1c  this issues resolved successfully.

**Comment by arsen1c** [comment]
Hi @harshmangalam, I am not able to sign in or sign up when I run the app locally. I get 404 in the response.  Do I need to setup the backend? Below is the response screenshot. Also, the client is running on localhost:3000.

image

**Comment by harshmangalam** [comment]
No need to setup backend add small changes in .env file

`.env`
```
VITE_ENDPOINT=https://hydrogen-harsh.herokuapp.com/api

```

**Comment by harshmangalam** [comment]
If you are interested in backend then you can look into https://github.com/harshmangalam/hydrogen-nodejs-server

**Comment by arsen1c** [comment]
@harshmangalam Awesome! I will make changes in `.env`. Also, I will definitely checkout the backend code, thanks for sharing!

**Review by harshmangalam — COMMENTED** [review]
Approved and deployed

**Pull request merged**
