### PR TITLE
fixed the issue of tooltip for mobile responsivness

### PR DESCRIPTION
**Pull request by somenath203**
I have fixed the issue regarding the tooltip for mobile responsiveness

Screenshot (161)

### CODE REVIEW

**Comment by harshmangalam** [comment]
Here post card design is breaking on mobile screen.

**Comment by somenath203** [comment]
> Here post card design is breaking on mobile screen.

I don't know tailwind css, that's why I can't fix it.

**Comment by harshmangalam** [comment]
Learning and working with tailwindcss is fun take your time and learn . Because it is framework agnoistic you can use it with any framework.

**Comment by somenath203** [comment]
> Learning and working with tailwindcss is fun take your time and learn . Because it is framework agnoistic you can use it with any framework.

Yes. I will start learning tailwind css soon.

**Pull request closed without merging**
