### PR TITLE
Implemented spinner in create button and disabled button

### PR DESCRIPTION
**Pull request by Siddharth9890**
Done with #46

### CODE REVIEW

**Comment by harshmangalam** [comment]
Use classList instead of putting dynamic classes in className for better optimization

**Comment by Siddharth9890** [comment]
Can you explain more about class list and how to use it because i have never heard of class list before

**Comment by Siddharth9890** [comment]
image
Like this @harshmangalam

**Comment by harshmangalam** [comment]
Yes but in place of class you will put classList
like this


```jsx
<button
disabled={loading()}
type="submit"
className="flex justify-center w-full s py-2 px-3 bg-blue-500 text-white rounded-lg text-lg"
classList={{"opacity-60":loading()}}>

<Show
  when={!loading()}
  fallback={<ImSpinner2 className="animate-spin w-8 h-8" />}>
  Create
</Show>
</button>

```

**Review by harshmangalam — APPROVED** [review]
Approved

**Pull request merged**
